apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-trading-bot
  labels:
    app: crypto-trading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-trading-bot
  template:
    metadata:
      labels:
        app: crypto-trading-bot
    spec:
      containers:
      - name: trading-bot
        image: your-registry/crypto-trading-bot:latest
        imagePullPolicy: Always
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: BINANCE_API_KEY
          valueFrom:
            secretKeyRef:
              name: binance-credentials
              key: api-key
        - name: BINANCE_API_SECRET
          valueFrom:
            secretKeyRef:
              name: binance-credentials
              key: api-secret
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: monitoring-secrets
              key: slack-webhook
        ports:
        - containerPort: 8000
          name: metrics
        - containerPort: 8080
          name: health
        volumeMounts:
        - name: config
          mountPath: /app/config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: trading-bot-config